### ISSUE TITLE
Google Play Services Plugins

### ISSUE THREAD

**Issue by farmerbb** [pyricau/androidsrc#9]
While it's true that the vast majority of Google Play Services is closed source, there are a small number of Gradle plugins related to Play Services that Google has open-sourced, including the oss-versions-plugin and a couple others.  Might be worth making a small note about this in the Google Play Services section at the bottom.

https://github.com/google/play-services-plugins

**Comment by pyricau** [comment]
Ah, cool! Want to open up a PR?
